name: Deploy on PR merge

on:
  pull_request:
    types: [closed]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-info.outputs.version }}
      name: ${{ steps.package-info.outputs.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Build example
        run: npm run build:example -- --base=/vue-spinkit/

      - name: Run smoke tests
        run: npm test

      - name: Extract package info
        id: package-info
        run: |
          echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Upload library build artifact
        uses: actions/upload-artifact@v4
        with:
          name: library-build
          path: build/
          retention-days: 7

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  check-version:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      should-publish: ${{ steps.version-check.outputs.should-publish }}
    steps:
      - name: Check if version exists on npm
        id: version-check
        run: |
          PKG_NAME="${{ needs.build.outputs.name }}"
          LOCAL_VERSION="${{ needs.build.outputs.version }}"
          echo "Package: $PKG_NAME, Local version: $LOCAL_VERSION"
          
          REMOTE_VERSION=$(npm view "$PKG_NAME" version 2>/dev/null || echo "")
          if [ -n "$REMOTE_VERSION" ]; then
            echo "Remote version: $REMOTE_VERSION"
          else
            echo "Remote version: not found"
          fi
          
          if [ "$REMOTE_VERSION" = "$LOCAL_VERSION" ]; then
            echo "Version unchanged; skipping npm publish"
            echo "should-publish=false" >> $GITHUB_OUTPUT
          else
            echo "Version changed; will publish to npm"
            echo "should-publish=true" >> $GITHUB_OUTPUT
          fi

  deploy-github-pages:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  publish-npm:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master' && needs.check-version.outputs.should-publish == 'true'
    needs: [build, check-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Download library build artifact
        uses: actions/download-artifact@v4
        with:
          name: library-build
          path: ./build

      - name: Pre-publish diagnostics
        run: |
          echo "=== npm whoami ==="
          npm whoami || echo "Not authenticated"
          
          echo "=== Package info ==="
          echo "Name: ${{ needs.build.outputs.name }}"
          echo "Version: ${{ needs.build.outputs.version }}"
          
          echo "=== Current npm registry info (if exists) ==="
          npm view "${{ needs.build.outputs.name }}" || echo "Package not found on registry"
          
          echo "=== Files to be published ==="
          npm pack --dry-run
          
          echo "=== Verifying build directory ==="
          ls -la build/

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build.outputs.version }}
          name: Release v${{ needs.build.outputs.version }}
          body: |
            Release version ${{ needs.build.outputs.version }}
            
            Changes merged from PR #${{ github.event.pull_request.number }}
          draft: false
          prerelease: false
